### ISSUE TITLE
xamarin-bluetooth-le ver. 2.2.0-pre2 and iOS

### ISSUE THREAD

**Issue by Auto72** [dotnet-bluetooth-le/dotnet-bluetooth-le#476]
Using the xamarin-bluetooth-le ver. 2.1.1, my app is working fine in Android and iOS.
If I use the xamarin-bluetooth-le ver. 2.2.0-pre2, my app works on Android but not in iOS 14.2 (iPhone 8) because every time I try to connect to the BLE device, I get the following error:

Exception --> Value cannot be null. Parameter name: source

await _adapter.ConnectToDeviceAsync(device, new ConnectParameters(false, false), _cancelSource.Token); 

I'm using the Vanilla version of the Plugin.BLE.

**Comment by smsissuechecker** [comment]
Hi @Auto72,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Auto72** [comment]
No I did not use the template. It is not useful for report this kind of issue, this time.
