### ISSUE TITLE
Compatibility with WatchOS?

### ISSUE THREAD

**Issue by nowlights** [dotnet-bluetooth-le/dotnet-bluetooth-le#539]
Does it work on WatchOS?

**Comment by smsissuechecker** [comment]
Hi @nowlights,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
