### ISSUE TITLE
It is not possible to execute different StartScanningForDevicesAsync

### ISSUE THREAD

**Issue by vitalii-vov** [dotnet-bluetooth-le/dotnet-bluetooth-le#550]
Hello.
My task is to make an application to which you can connect a large number of devices from different manufacturers.
Some devices need to be scanned by name, and some by service.

For each of the devices, I have written my own class, which itself is engaged in scanning and automatic connection to the device.

The problem is that the call to the await method await _adapter.StartScanningForDevicesAsync(guids); from different classes causes the scan to stop working. For example, if you perform scanning by Guids of services in the first class, and without Guids in the second, then the second scan will also work according to the rules of the first.
On the one hand, this is to be expected, since we are getting a singleton from CrossBluetoothLE.Current.Adapter, but on the other hand, maybe there is a way to start two separate function calls, or create a second instance of Adapter?

## Steps to reproduce

1. Create two classes for working with devices.
```C#
// Allows you to work with all thermometers. Scans devices by service.
public class Thermometer
{
   private Guid SR_THERMOMETER = Guid.Parse("00001809-0000-1000-8000-00805f9b34fb");
   private IAdapter _adapter;

   public async Task Init()
   {
      _adapter = CrossBluetoothLE.Current.Adapter;
      _adapter.ScanTimeout = 30 * 1000;
      _adapter.DeviceDiscovered += OnDeviceDiscoveredAsync;
      _adapter.ScanTimeoutElapsed += OnScanTimeoutElapsedAsync;
      await StartScan();
   }

   private async Task StartScan()
   {
      //  Scans devices by service.
      var guids = new Guid[] { SR_THERMOMETER };
      await _adapter.StartScanningForDevicesAsync(guids);
   }

   private async void OnDeviceDiscoveredAsync(object sender, DeviceEventArgs e)
   {
      Debug.WriteLine($"Thermometer: {e.Device.Name}");
      // todo:
   }
   private async void OnScanTimeoutElapsedAsync(object sender, EventArgs e)
   {
      await StartScan();
   }
}

//Allows you to work with a specific device. Scans devices all devices and selects those that pass the filter by name.
public class Tonometer
{
   private const string DEVICE_NAME_START = "A&D_UA";
   private IAdapter _adapter;

   public async Task Init()
   {
      _adapter = CrossBluetoothLE.Current.Adapter;

      _adapter.ScanTimeout = 30 * 1000;
      _adapter.DeviceDiscovered += OnDeviceDiscoveredAsync;
      _adapter.ScanTimeoutElapsed += OnScanTimeoutElapsedAsync;
      await _adapter.StartScanningForDevicesAsync();
   }

   private async Task StartScan()
   {
      //  Scans all devices
      await _adapter.StartScanningForDevicesAsync();
   }

   private async void OnDeviceDiscoveredAsync(object sender, DeviceEventArgs e)
   {
      Debug.WriteLine($"Thermometer: {e.Device.Name}");
      if (string.IsNullOrEmpty(device.Name) || !device.Name.StartsWith(DEVICE_NAME_START))
         return;
       // todo:
   }
   
   private async void OnScanTimeoutElapsedAsync(object sender, EventArgs e)
   {
      await StartScan();
   }
}
```

2. In the application class, we create instances of our devices and start scanning.

```C#
public partial class App : Application
{
   Thermometer _thermometer;
   Tonometer _tonometer;

   public App()
   {
      InitializeComponent();
      _thermometer = new Thermometer();
      _tonometer = new Tonometer();
   }

   protected override async void OnStart()
   {
      await _thermometer.Init();
      await _tonometer.Init();
   } 
}
```

## Expected behavior
Device scanning should work in different classes independently of other classes.
For the Thermometer class, only devices containing the "00001809-0000-1000-8000-00805f9b34fb" service should be scanned. For the Tonometer class, all devices regardless of services.

## Actual behavior
Scanning follows the pattern of the first call to the StartScanningForDevicesAsync function.

## Configuration

**Version of the Plugin:** 2.1.2

**Platform:** Android 10

**Device:** Xiaomi Mi A2

**Comment by smsissuechecker** [comment]
Hi @vitalii-vov,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by axa88** [comment]
Should probably close this.
The use of Scanning in the given example is inappropriate.
