### ISSUE TITLE
MAUI compatibility?

### ISSUE THREAD

**Issue by SanjayP1234007** [dotnet-bluetooth-le/dotnet-bluetooth-le#622]
Hi Sven-Michael,

Can this plugin be used for .NET MAUI, as i am migrating my Xamarin code to MAUI.but when i do this i am getting the following message:

"This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

**Comment by smsissuechecker** [comment]
Hi @SanjayP1234007,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by TimoKinnunen** [comment]
Try this and adopt code from it!

MauiXAMLBluetoothLE

.Net MAUI app using Plugin.BLE for Polar H10 Heart Rate Sensor. Bluetooth LE working solution on Android. I must ask James Montemagno for help to get permissions right on iOS and Windows.

To read code and understand it is simple.

This app might bring closer Bluetooth LE to .Net MAUI. I hope so.

https://github.com/TimoKinnunen/MauiXAMLBluetoothLE

**Comment by janusw** [comment]
> Can this plugin be used for .NET MAUI, as i am migrating my Xamarin code to MAUI.but when i do this i am getting the following message:

Not yet, but there is PR #614, which updates it to .NET 6 (thus making it compatible for use with MAUI). Hope it will be merged soon.

**Comment by janusw** [comment]
It seems that #614 did actually not fix this problem, but #638 should.

@SanjayP1234007, can you confirm that your problem is gone on current master? (using the nupkg from here: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/3470893880#artifacts)

**Comment by janusw** [comment]
Since we have sufficient evidence by now that this kind of problem is fixed via #638 (both on iOS and Windows), I will close this issue. In case the problem persists, please open a new issue (with more details preferably).
