### ISSUE TITLE
Addition of information to readme doc

### ISSUE THREAD

**Issue by joeholdsworth** [dotnet-bluetooth-le/dotnet-bluetooth-le#629]
Hi,

For the readme would it be possible to add a bit more information over the example app.

I've installed the plugin...

How do I now use the example app, is it everything in the source folder I need, could you just add a few steps on which folder has the example in or notes on the folder structure.

Really looking forward to trying this thank you

**Comment by smsissuechecker** [comment]
Hi @joeholdsworth,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
> How do I now use the example app, is it everything in the source folder I need, could you just add a few steps on which folder has the example in or notes on the folder structure.

There is a (short) description of the sample app at https://github.com/xabre/xamarin-bluetooth-le#sample-app

The source of the sample is in https://github.com/xabre/xamarin-bluetooth-le/tree/master/Source/BLE.Client

To build the sample app, you can just open https://github.com/xabre/xamarin-bluetooth-le/blob/master/Source/BLE.sln, it has all the libs and the sample code.

Is that what you want to know?

**Comment by joeholdsworth** [comment]
Hi,

Yes thank you,

Joe

**Comment by janusw** [comment]
Alright then. Closing.
