### ISSUE TITLE
Crashes when device already disconnected

### ISSUE THREAD

**Issue by naryk86** [dotnet-bluetooth-le/dotnet-bluetooth-le#631]
Hello,
I've created an app two years ago with Xamarin to connect to custom ble devices: the app searches for ble devices and try to connect to the one chosen and the request its characteristics.
 At the disconnection, my app tries continuosly to connect to devices that we're previously connected (so that it will be connected immediately after switching without other operation from the user).
Unfortunately it seems that -after the device is disconnected (by switching off)- the app enters in a strange loop and suddenly crashes. It happens only in iOS, not Android.
I found that only immediately before crashes the log show me the following error, several time for second:
Device XXXXXXXX disconnected while fetching services.
As if the plugin ble adapter successfully found a way to connect to the device (which is switched off, so: no way) and then started to request bluetototh characteristics
 

## Steps to reproduce

1.Connect to ble devices

2. Switch off ble devices and wait for disconnection

3. wait

## Expected behavior
App does not crashes when device are disconnected

## Actual behavior
App crashes after a few seconds

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration
These crashes happens only on iOS devices and only recently (I suppose, few months).
I use iOS 15.6.1 to test my code.
The problem occur with the 2.1.1 version of the plugin (the one that I use when started writing my app in 2020) and also in 2.1.3

**Comment by smsissuechecker** [comment]
Hi @naryk86,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
