### ISSUE TITLE
Unable to Find MAC Address in IOS in Xamarin Forms

### ISSUE THREAD

**Issue by SanjayP1234007** [dotnet-bluetooth-le/dotnet-bluetooth-le#643]
Hi,

I am using Plugin.BLE, I am facing one issue, I am unable to get Mac Id of the discovered devices by advertisements. Amazing fact is i am able to get Mac address of discovered devices in Android. I am using same plugin for both. can you help me in this issue or suggest me how can i get Mac address of discovered devices in IOS xamarin forms. In Android version, it is available in "e.Device.NativeDevice" which I get from advertisements but in IOS plugin i am unable to get Mac address of discovered devices.

Please help me in it, if there is any solution for it.

**Comment by janusw** [comment]
Duplicate of #645.
