### ISSUE TITLE
Android 13 Scan issue

### ISSUE THREAD

**Issue by 88souls** [dotnet-bluetooth-le/dotnet-bluetooth-le#651]
After install Android 13, SDK 33, There is no results in DeveceDiscovered.

I`m sure device is available for scaning and it near me. I can see it from phone bluetooth settings/ Device is ble.
Bluetooth is On and permissions are done in manifest and runtime. Bluetooth.Scan/advertize/admin/previleged/connect.Location permissions, nearby devices/hardware.bluetooth_le etc.
  
Anybody implement it on Android 13? Where can be a problem

**Comment by smsissuechecker** [comment]
Hi @88souls,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
Which version of Plugin.BLE are you using?

If scanning does not work, the first guess is usually permissions (the runtime permissions on Android 12+ can be nontrivial to get right). Or did you possibly set a scanning filter that would exclude the device that you're trying to see?

You could check if our sample client works for you: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/tree/master/Source/BLE.Client (It currently targets Android 12, but that shouldn't make too much of a difference. Also we can upgrade it to Android 13 if necessary.)

And yes, for me scanning with Plugin.BLE works on Android 13.

**Comment by TahaZahit** [comment]
I faced the same problem, if you are not using it, remove the following trace from the manifest and change the android permission part as follows.
```
//remove this permission
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
```


```
//change your android required permissions like that:
 public override (string androidPermission, bool isRuntime)[] RequiredPermissions => new List<(string androidPermission, bool isRuntime)>
    {
        (Android.Manifest.Permission.BluetoothScan, true),
        (Android.Manifest.Permission.BluetoothConnect, true)

    }.ToArray();
```

**Comment by janusw** [comment]
> I faced the same problem, if you are not using it, remove the following trace from the manifest and change the android permission part as follows.
> 
> ```
> //remove this permission
> <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
> ```

Hm, I don't think having this should be a problem.


> ```
> //change your android required permissions like that:
>  public override (string androidPermission, bool isRuntime)[] RequiredPermissions => new List<(string androidPermission, bool isRuntime)>
>     {
>         (Android.Manifest.Permission.BluetoothScan, true),
>         (Android.Manifest.Permission.BluetoothConnect, true)
> 
>     }.ToArray();
> ```

Yes, you need to request these permissions at runtime on Android 12 & 13. Ideally they should be included in Microsoft.Maui.ApplicationModel.Permissions. I opened a PR in MAUI to support these permissions: 
https://github.com/dotnet/maui/pull/12413

**Comment by erdmenchen** [comment]
I had the same Problem, only after disabling and enabling Bluetooth on the smartphone once, it started to work again...

**Comment by Auto72** [comment]
I can confirm, in a MAUI project, on Android 13 the scan doesn't work.
The following events aren't fired:

DeviceDiscovered() 
DeviceAdvertised()

**Comment by Auto72** [comment]
The permissions for Android are teken from this project:

https://github.com/jamesmontemagno/MauiApp-DI

**Comment by 88souls** [comment]
So i fix this in my code, here is some things i did:
1) Manifest:
<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
	<uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />
	<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
	<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-feature android:name="android.hardware.bluetooth" android:required="true" />
	<uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />
	<uses-feature android:name="android.software.companion_device_setup" />
	<uses-feature android:name="android.hardware.location" android:required="false" />

2) Additionaly there is permission called in phone "NEARBY DEVICES". You should ask user in runtime from ANDROID project, I ask from additional service. Permissions namespace Xamarin.Essensials (From core I use Plugin.Permissions and its ok):

public async Task<PermissionStatus> CheckAndRequestBluetoothPermissions()
        {
            PermissionStatus status;
            if (Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.S)
            {
                status = await Permissions.CheckStatusAsync<BluetoothSPermission>();

                if (status == PermissionStatus.Granted)
                    return status;
                AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(this._activity);
                alertDialogBuilder.SetTitle(Localization["Permission required"]);
                
                alertDialogBuilder.SetIcon(Resource.Drawable.ic_alert);
                alertDialogBuilder.SetMessage(Localization["BluetoothPermissions"]);
                alertDialogBuilder.SetCancelable(false);
                alertDialogBuilder.SetPositiveButton(Localization["Ok"], async (senderAlert, args) =>
                {
                    status = await Permissions.RequestAsync<BluetoothSPermission>();
                    alertDialogBuilder.Dispose();
                });
                alertDialogBuilder.SetNegativeButton(Localization["Cancel"], async (senderAlert, args) =>
                {
                    alertDialogBuilder.Dispose();
                });

                Dialog diag = alertDialogBuilder.Create();
                
                diag.Show();
                
            }
            else
            {
                status = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();

                if (status == PermissionStatus.Granted)
                    return status;

                InvokeOnMainThread(() =>
                {
                    AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(this._activity);
                    alertDialogBuilder.SetTitle(Localization["Permission required"]);
                    alertDialogBuilder.SetIcon(Resource.Drawable.ic_alert);
                    alertDialogBuilder.SetMessage(Localization["LocationWhenInUse"]);
                    alertDialogBuilder.SetCancelable(false);
                    alertDialogBuilder.SetPositiveButton(Localization["Ok"], async (senderAlert, args) =>
                    {
                        status = await Permissions.RequestAsync<Permissions.LocationWhenInUse>();
                        alertDialogBuilder.Dispose();
                    });
                    alertDialogBuilder.SetNegativeButton(Localization["Cancel"], async (senderAlert, args) =>
                    {
                        alertDialogBuilder.Dispose();
                    });
                    Dialog diag = alertDialogBuilder.Create();
                    diag.Show();
                });
            }
            return status;

After all this things, it starts work. Note if you dont have exeptions, but DeviceDiscovered() and
DeviceAdvertised() not starts, its permissions issue. 
I hope you will be OK with this

**Comment by 88souls** [comment]
1. Manifest:
android:minSdkVersion="28" android:targetSdkVersion="33"
android.permission.ACCESS_NETWORK_STATE"
android.permission.INTERNET"
android.permission.BLUETOOTH" android:maxSdkVersion="30"
android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30"
android.permission.BLUETOOTH_PRIVILEGED"
android.permission.BLUETOOTH_CONNECT"
android.permission.BLUETOOTH_ADVERTISE"
android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"
android.permission.ACCESS_COARSE_LOCATION"
android.permission.ACCESS_FINE_LOCATION"
uses-feature android:name="android.hardware.bluetooth" android:required="true"
uses-feature android:name="android.hardware.bluetooth_le" android:required="true"
uses-feature android:name="android.software.companion_device_setup"
uses-feature android:name="android.hardware.location" android:required="false"
