### ISSUE TITLE
ScanFilterOptions.ManufacturerIds from the github repository description does not exist anymore

### ISSUE THREAD

**Issue by janseris** [dotnet-bluetooth-le/dotnet-bluetooth-le#658]
## Steps to reproduce

1.  Create new MAUI .NET 7 App
2. paste `scanFilterOptions.ManufacturerIds = new [] {1,2,3,etc}; // android only filter in source code when Plugin.BLE is installed`

## Expected behavior
ScanFilterOptions.ManufacturerIds exists in Plugin.BLE library

## Actual behavior
Compile-time error with it not existing

## Configuration

Plugin.BLE 2.1.3

**Comment by smsissuechecker** [comment]
Hi @janseris,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janseris** [comment]
> You haven't used our issue template
I have but deleted unnecessary parts

**Comment by janusw** [comment]
You're right, `ManufacturerIds` was replaced by the more general `ManufacturerDataFilters` in 5cd2ce5c026b7d569ae5a742805a627b9b857e1f.

(Use the source, Luke: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/master/Source/Plugin.BLE/Shared/ScanFilterOptions.cs)

So yes, the scan filtering section in the ReadMe needs an update.

**Comment by janusw** [comment]
Fixed on master via 87d5e73f221f570c8bc7b88db09dd85f901b4fc6. Thanks for reporting!
