### ISSUE TITLE
[Question] Is there a way to continue scanning for devices in doze mode?

### ISSUE THREAD

**Issue by tmacintosh** [dotnet-bluetooth-le/dotnet-bluetooth-le#663]
Does the Plugin.BLE library support scanning for devices in doze mode?

I'm working on a .Net7 Maui app (just Android at this stage) to create an IoT solution and have managed to successfully detect, connect, get services, and read characteristics of a device. However, whenever my app loses focus the library stops returning discovered devices. As soon as the app returns to the foreground, detections start flowing in again.

I have tried calling the library from a Foreground Service but still had no luck there. So I then tried implementing a native Android BLE scanner and was able to receive detections when my app was not in the foreground.

Ultimately I'm hoping to have the app continue detecting devices while in doze mode, and I'm hoping this is achievable using this library before I have to go and build my own library from scratch.

Thanks in advance

**Comment by smsissuechecker** [comment]
Hi @tmacintosh,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
It should be possible to continue scanning for devices when the app is in the background or when the screen is off (both on Android and iOS), but IIRC you need to use a scan filter.

Note that the scanning rate may be reduced when the app is not in the foreground.
