### ISSUE TITLE
In iOS: System.NotImplementedException

### ISSUE THREAD

**Issue by ckrutsinger** [dotnet-bluetooth-le/dotnet-bluetooth-le#666]
Have been using Plugin.BLE in Android successfully and now trying to use in iOS version of same MAUI app. However, is crashing on app launch with System.NotImplementedException

## Steps to reproduce

1. Call to `CrossBluetoothLE.Current.Adapter` throws System.NotImplementedException in iOS 16.3.1

## Expected behavior
Should return a singleton instance of BLE adapter

## Actual behavior
throws System.NotImplementedException in iOS

### Crashlog

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  at at Plugin.BLE.CrossBluetoothLE.get_Current()

## Configuration

**Version of the Plugin:** 2.1.3

**Platform:** iOS 16.3.1

**Device:** iPhone XR

**Comment by smsissuechecker** [comment]
Hi @ckrutsinger,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
For MAUI, you'll need to use a 3.0 beta version. 2.1.3 does not support .NET 6 and MAUI yet. Can you confirm that the error goes away with 3.0.0-beta.2?

**Comment by ckrutsinger** [comment]
3.0.0-beta.2 did in fact stop the crashing. Thank you!
