### ISSUE TITLE
Device.ParseScanRecord throws System.ArgumentException: length

### ISSUE THREAD

**Issue by TomasMalcanek** [dotnet-bluetooth-le/dotnet-bluetooth-le#676]
The Device.ParseScanRecord(System.Byte[] scanRecord) method is throwing a System.ArgumentException: length exception. This issue seems to occur after the OnDeviceDiscovered callback is called.

## Steps to reproduce

1. Start the app on the affected device(s) (Honor 50 Lite - Android 11, Galaxy A53 5G - Android 13)
2. Wait for the OnDeviceDiscovered callback to be called.
3. Attempt to call the Device.ParseScanRecord method with a byte array as the scanRecord argument.

## Expected behavior
The Device.ParseScanRecord method should be able to parse the byte array without throwing an exception.

## Actual behavior
The Device.ParseScanRecord method is throwing a System.ArgumentException: length exception.

### Crashlog

```
Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length)
Device.ParseScanRecord (System.Byte[] scanRecord)
Plugin.BLE.Android.Device..ctor (Plugin.BLE.Android.Adapter adapter, Android.Bluetooth.BluetoothDevice nativeDevice, Android.Bluetooth.BluetoothGatt gatt, System.Int32 rssi, System.Byte[] advertisementData) [0x00017] in <e84f194db96045279f39298a58a796ea>:0
Adapter+Api21BleScanCallback.OnScanResult (Android.Bluetooth.LE.ScanCallbackType callbackType, Android.Bluetooth.LE.ScanResult result)
ScanCallback.n_OnScanResult_ILandroid_bluetooth_le_ScanResult_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 native_callbackType, System.IntPtr native_result)
```

## Configuration

**Version of the Plugin:** 2.1.3

**Platform:** Android 11 / Android 13

**Device:** Honor 50 Lite, Galaxy A53 5G

**Comment by smsissuechecker** [comment]
Hi @TomasMalcanek,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by TomasMalcanek** [comment]
I couldn't find this issue here before, but it's an duplicate of [#567
](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/567)
