### ISSUE TITLE
Rename supportsCodedPHY and supportsExtendedAdvertising

### ISSUE THREAD

**Issue by felipemomm** [dotnet-bluetooth-le/dotnet-bluetooth-le#693]
Well, as the title says, please rename the methods supportsCodedPHY/supportsExtendedAdvertising to SupportsCodedPHY/SupportsExtendedAdvertising to follow C# pattern.

**Comment by janusw** [comment]
My bad, I guess I was a bit sloppy about coding style in #679. Will fix.

And now you got me thinking whether we should take any measures to check (and fix) coding style in an automated fashion, e.g. via `dotnet format` or similar. Comments/suggestions welcome.

**Comment by janusw** [comment]
The fix is available in [3.0.0-beta.5](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/releases/tag/3.0.0-beta.5).
