### ISSUE TITLE
[INFO/WARN] Your `LICENSE` does not include your copyright information!!

### ISSUE THREAD

**Issue by MDale-RAC** [dotnet-bluetooth-le/dotnet-bluetooth-le#694]
I noticed you still have the boilerplate copyright attributions in your license:
https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/6db69213489225448393a6d77bb8a3984d242e3d/LICENSE#L189

Please update your `LICENSE`! (See: [L180](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/6db69213489225448393a6d77bb8a3984d242e3d/LICENSE#L180)-187)

I appreciate the work you've done with this project and would like to ensure we are able to properly provide attributions to your efforts when the time comes!

**Comment by smsissuechecker** [comment]
Hi @MDale-RAC,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
You're absolutely right, thanks for noticing. I will fix it.

**Comment by janusw** [comment]
Fixed via d5315bf2bfdc838f1f33b02eb386a278ed016019.
