### ISSUE TITLE
Could not resolve type with token

### ISSUE THREAD

**Issue by nowlights** [dotnet-bluetooth-le/dotnet-bluetooth-le#699]
I bind the values in a class when starting the application:

BLEt.bluetoothLE = CrossBluetoothLE.Current;
             BLEt.Adapter = CrossBluetoothLE.Current.Adapter;
             BLEt.list = new ObservableCollection<IDevice>();

             BLEtPiggy.bluetoothLE = CrossBluetoothLE.Current;
             BLEtPiggy.Adapter = CrossBluetoothLE.Current.Adapter;
             BLEtPiggy.list = new ObservableCollection<IDevice>();

but, i have an error:

## Actual behavior
Error in load assembly!?

### Crashlog

System.TypeLoadException: Could not resolve type with token 01000051 from typeref (expected class 'Plugin.BLE.Abstractions.Contracts.IBluetoothLE' in assembly 'Plugin.BLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null')

## Configuration

**Version of the Plugin:** 3.0.0.beta4

**Platform:** e.g. All android 11, or better

**Comment by smsissuechecker** [comment]
Hi @nowlights,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
