### ISSUE TITLE
DeviceConnected event not fired

### ISSUE THREAD

**Issue by smersh1307n2** [dotnet-bluetooth-le/dotnet-bluetooth-le#714]
Plugin.BLE 3.0.0-beta.4
MAUI .NET7.

When connecting to iDevice, the Adapter.DeviceConnected event is fired. If you disconnect from iDevice, the Adapter.DeviceDisconnected event is fired. If I connect again to iDevice, the event Adapter.DeviceConnected  is not fired.

_Ble.Adapter.ConnectToDeviceAsync(this._IDevice); 
//event fired
//wait
_Ble.Adapter.DisconnectDeviceAsync(this._IDevice); //event fired
event fired
//wait
_Ble.Adapter.ConnectToDeviceAsync(this._IDevice);
event not fired

**Comment by smsissuechecker** [comment]
Hi @smersh1307n2,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
