### ISSUE TITLE
DeviceConnected event not fired

### ISSUE THREAD

**Issue by smersh1307n2** [dotnet-bluetooth-le/dotnet-bluetooth-le#715]
When connecting to iDevice, the Adapter.DeviceConnected event is fired. If you disconnect from iDevice, the Adapter.DeviceDisconnected event is fired. If I connect again to iDevice, the event Adapter.DeviceConnected is not fired.

## Steps to reproduce
1.Start scan devices
2.Wait
3.Get IDevice bluetoothLE.
4.Connecting to IDevice. =>fired event Adapter.DeviceConnected
5.Wait
6.Disconnecteted from IDevice =>fired event Adapter.DeviceDisconnected
7.Wait
8.Connecting to IDevice. =>not fired event Adapter.DeviceConnected
 ## Expected behavior
Event must fired
## Actual behavior
Event not fired
### Crashlog
not available
## Configuration
Version of the Plugin: 3.0.0-beta.4

Platform: Windows 10

Device: PC

**Comment by smsissuechecker** [comment]
Hi @smersh1307n2,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
