### ISSUE TITLE
Add support for RequestMtuAsync on Windows

### ISSUE THREAD

**Issue by TravisRo** [dotnet-bluetooth-le/dotnet-bluetooth-le#727]
## Steps to reproduce

1. Create MAUI App targeting WIndows with BLE.Plugin library

2. Call RequestMtuAsync

3. -1 is returned

## Expected behavior
It should return the MTU size that windows has already negotiated.  Windows always tries to negotiate the maximum MTU size.

## Actual behavior
Function does nothing and returns -1

### Crashlog

None

## Configuration

**Version of the Plugin: 3.0.0-beta.5

**Platform: Windows

**Device: ESP32 MINI-01

**Comment by smsissuechecker** [comment]
Hi @TravisRo,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
Fixed via #728.
