### ISSUE TITLE
Inquiry Regarding 'ShouldQueueOnMainThread' and GATT Status 133 on Samsung Galaxy S20 and above

### ISSUE THREAD

**Issue by 92-Theo** [dotnet-bluetooth-le/dotnet-bluetooth-le#743]
Hello,

I've been working with your BLE library for Xamarin, and it's been incredibly helpful. I have a couple of questions that I'd appreciate your insight on:

1. Regarding 'ShouldQueueOnMainThread': Could you please explain the rationale behind adding the 'ShouldQueueOnMainThread' field in the BleImplementation class? I'm particularly interested in understanding the problems it was designed to solve or any performance improvements it offers.

2. GATT Status Code 133 on Samsung Galaxy S20 and Above: I've noticed that on Samsung Galaxy S20 and newer models, GATT status code 133 occasionally occurs. When this happens, it renders all GATT-related apps on Android non-functional until the system is rebooted. Does the 'ShouldQueueOnMainThread' option have any relation to this issue, or is it designed to alleviate such problems? If not, do you have any suggestions on how to handle this?

I appreciate any guidance you can provide on these issues.

Best regards,

**Comment by smsissuechecker** [comment]
Hi @92-Theo,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by 92-Theo** [comment]
move to 'Discussions'
