### ISSUE TITLE
StartScanningForDevicesAsync while the screen is off or app is minimized on Android

### ISSUE THREAD

**Issue by yasserjarouf** [dotnet-bluetooth-le/dotnet-bluetooth-le#750]
The **StartScanningForDevicesAsync** doesn't detected devices while the screen is off even if the **ScanFilterOptions** is passed with the correct Service Guid.

## Expected behavior
The adapter to discover the device even if the screen is off (and while in foreground service).

## Actual behavior
It's not detecting the device while the screen is off or the app is invisible, actually, if the app screen is on and visible, the device is detected fine with the filter, there is a loop of discovering the device over and over and a sound alert is fired accordingly.

Once the device screen is switched off, the loop still works fine and the device is discovered, but after few seconds (around 20-30) the adapter is not able to discover the device unless the screen is on and the app is on active screen.

Not sure what am I missing, any suggestions? Maybe some permissions are needed?

**Version of the Plugin:** 2.1.3

**Platform:** Android 10

**Device:** Galaxy Note 9

**Comment by smsissuechecker** [comment]
Hi @yasserjarouf,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
> The **StartScanningForDevicesAsync** doesn't detected devices while the screen is off even if the **ScanFilterOptions** is passed with the correct Service Guid.
> ## Expected behavior
> 
> The adapter to discover the device even if the screen is off (and while in foreground service).

With a scan filter, this should actually work. One suggestion ...

> **Version of the Plugin:** 2.1.3

... Could you maybe try a newer version of the plugin, ideally the recent 3.0.0-rc.1?

And a question: 

> **Platform:** Android 10

Are you actually *targeting* Android 10, i.e. API level 29? Or just running on an Android 10 device?

If the latter, which SDK level are you targeting?

**Comment by yasserjarouf** [comment]
Nothing, still same behavior.
> ... Could you maybe try a newer version of the plugin, ideally the recent 3.0.0-rc.1?

This setup I just tested with same issue `<uses-sdk android:minSdkVersion="28" android:targetSdkVersion="33" />`
> And a question:
> 
> > **Platform:** Android 10
> 
> Are you actually _targeting_ Android 10, i.e. API level 29? Or just running on an Android 10 device?
> 
> If the latter, which SDK level are you targeting?

**Comment by yasserjarouf** [comment]
I have found my issue. 

It's with the App permissions. I had to set it for the **Location Access** to be **Allow all the time**!

I hope it helps whomever may come across this confusion. 😊

Just something I noticed, I had to unlock my phone after the phone reboots as I'm using a Foreground Service with a Boot Recei
