### ISSUE TITLE
plugin ble 3.00 / .NET MAUI Throw Exception 

### ISSUE THREAD

**Issue by ichirou2020** [dotnet-bluetooth-le/dotnet-bluetooth-le#760]
The plugin ble 3.00 & Windows11 (.NET MAUI)
Crash when using StartUpdatesAsync() method in Windows 11
Android not Crashed.

plugin ble 2.13 & Android is no problem.
plugin ble 3.00 & Android ,Other methods seem to work fine

## Steps to reproduce

1.Use V2.1.3

2.nuget use .Verup 3.00

3.build and run windows 

## Expected behavior
In this code <b> await _characteristicread.StartUpdatesAsync(); </b> Throws Exception.
The same Throws  occurs in the StartUpdatesAsync() method in the sample app.
```
try
{
	Debug.WriteLine("受信可能になった");
	_characteristicread.ValueUpdated -= Characteristicread_ValueUpdated;    //ValueUpdateイベント削除
	_characteristicread.ValueUpdated += Characteristicread_ValueUpdated;    //ValueUpdateイベント登録
	await _characteristicread.StartUpdatesAsync();

}catch (Exception e)
{
	var msg = e.Message;
	Debug.WriteLine(msg);
}
```

## Actual behavior
Throws Exception 

### Crashlog

```
[StartUpdatesNativeAsync] failed with status: ProtocolError and protocol error Write Not Permitted
```

## Configuration

**Version of the Plugin:Plugin.BLE 3.0.0

**Platform:Windows11 22H2 22621.2428

**Device:DesktopPC( With Bluetooth dongle)/Note PC (Built-in Bluetooth)

**Comment by smsissuechecker** [comment]
Hi @ichirou2020,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by ichirou2020** [comment]
I want to Rewrite
