### ISSUE TITLE
How can I subscribe to a disconnection event

### ISSUE THREAD

**Issue by shijianoo** [dotnet-bluetooth-le/dotnet-bluetooth-le#787]
How can I subscribe to a disconnection event that triggers when Bluetooth is disconnected so I can do something later

**Comment by smsissuechecker** [comment]
Hi @shijianoo,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by shijianoo** [comment]
ok
