### ISSUE TITLE
when building sample Muai :	The type or namespace name 'Devices' does not exist in the namespace 'Windows'

### ISSUE THREAD

**Issue by ghisbo** [dotnet-bluetooth-le/dotnet-bluetooth-le#790]
Cannot build the sample on VS2022. i suppose there is some library more that i need ??

## Steps to reproduce

1. Open the sample from the github page in VS2022
2. install Plugin.ble v3.1.0 beta.1
3. build Ble.Client.maui project

## Expected behavior
i expect the sample would build as this should not be very old.

## Actual behavior
84 errors with  namespace errors like :
`Error	CS0234	The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)	Plugin.BLE (uap10.0.19041)	C:\Users\HP\source\repos\dotnet-bluetooth-le\Source\Plugin.BLE\Windows\Adapter.cs	13	Active	`

## Configuration

**Version of the Plugin:**  Plugin.ble 3.0

**Platform:** Win 11

**Device:**  PC HP

**Comment by smsissuechecker** [comment]
Hi @ghisbo,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
Probably some problem with the Windows SDK? Either it's missing completely or you have a wrong version. BLE.Client.Maui targets version 10.0.19041.

For me the MAUI sample client builds and runs well on Windows (with VS 2022 version 17.8.3), and it also builds alright in our CI.
