### ISSUE TITLE
How to show list of Bluetooth device names using Plugin.BLE in .net MAUI 8 - Android

### ISSUE THREAD

**Issue by Ganesh-210** [dotnet-bluetooth-le/dotnet-bluetooth-le#802]
I'm working on a Bluetooth project for **Android**. As now I can discovered list of devices but I'm not getting the Name. Please anyone help me to resolve this issue. It would be very helpful for me. 

FYI : Attached image below

**Note : I'm getting Rssi , ID and Native Device address**

` public ObservableCollection<IDevice> ScannedDevices { get; } = new ObservableCollection<IDevice>();`
  ```
  var ble = CrossBluetoothLE.Current;
    var adapter = CrossBluetoothLE.Current.Adapter;
    adapter.DeviceDiscovered += (s, e) =>
    {
        if (!ScannedDevices.Contains(e.Device))
        {
            ScannedDevices.Add(e.Device);
            string sss = e.Device.Name;
        }
    };

    adapter.StartScanningForDevicesAsync();
}
```

Steps to reproduce
Call this method on **Android** after you have already connected and paired a BLE device (BLE Just Works).

## Crashlog
Name cannot be null. 

## Expected behavior
On **Android**, it should return the list of the paired BLE devices. Device Name is null and its not showing
On **Android** the list of the paired BLE devices is returned . So I can pair the device.

## Actual behavior
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/155521009/2a726c97-40af-4579-8272-bb8f4d670bef)

## Configuration

**Version of the Plugin:** 3.1.0 

**Platform:** Android 13

**Device:** Moto E13

**Comment by smsissuechecker** [comment]
Hi @Ganesh-210,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Ganesh-210** [comment]
Done
