### ISSUE TITLE
Device Name is not showing in Android .net MAUI

### ISSUE THREAD

**Issue by Ganesh-210** [dotnet-bluetooth-le/dotnet-bluetooth-le#803]
I'm working on a Bluetooth project for **Android**. As now I can discovered list of devices but I'm not getting the Name. Please anyone help me to resolve this issue. It would be very helpful for me. 

FYI : Attached image below

**Note : I'm getting Rssi , ID and Native Device address**

` public ObservableCollection<IDevice> ScannedDevices { get; } = new ObservableCollection<IDevice>();`
  ```
  var ble = CrossBluetoothLE.Current;
    var adapter = CrossBluetoothLE.Current.Adapter;
    adapter.DeviceDiscovered += (s, e) =>
    {
        if (!ScannedDevices.Contains(e.Device))
        {
            ScannedDevices.Add(e.Device);
            string sss = e.Device.Name;
        }
    };

    adapter.StartScanningForDevicesAsync();
}
```

Steps to reproduce
Call this method on **Android** after you have already connected and paired a BLE device (BLE Just Works).

## Crashlog
Name cannot be null. 

## Expected behavior
On **Android**, it should return the list of the paired BLE devices. Device Name is null and its not showing
On **Android** the list of the paired BLE devices is returned . So I can pair the device.

## Actual behavior
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/155521009/2a726c97-40af-4579-8272-bb8f4d670bef)

## Configuration

**Version of the Plugin:** 3.1.0 

**Platform:** Android 13

**Device:** Moto E13

**Comment by smsissuechecker** [comment]
Hi @Ganesh-210,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by axa88** [comment]
There seems to be a couple of concerns with your report.
Firstly, what certainty do you have that all the devices around you even have a name?
Many don't.

Secondly, what is the expected influence on your outcome if any particular device is paired/connected, why note it?
A paired device may still advertise and be found by a scan.  And afaik a connected device most likely will not advertise and thus not be discovered.  Neither which influences if a device even has a name. 
At best Android can allow you to change the device `Ailias`, but you mention none of that here.

**Comment by Ganesh-210** [comment]
> There seems to be a couple of concerns with your report. Firstly, what certainty do you have that all the devices around you being scanned/discovered even have a name? Many don't.
> 
> Secondly, what is the expected influence on your outcome if any particular device is paired/connected, why note it? A paired device may still advertise and be found by a scan. And afaik a connected device most likely will not advertise and thus not be discovered. Neither which influences if a device even has a name. At best Android can allow you to change the device `Ailias`, but you mention none of that here.
> 
> Lastly, you already reported your "issue" #802

Thanks for the reply. I can get the name of paired Bluetooth devices.

I need to get all the Bluetooth Device Names which is nearby which is not paired.

` string _devname = e.Device.Name;` - Not getting all the device names and showing empty
` string _devid = e.Device.ID;` - Getting  all the device UUID's
` string _devrssi = e.Device.Rssi;` - Getting all the device Rssi's

**Comment by axa88** [comment]
> Thanks for the reply. I can get the name of paired Bluetooth devices.

What is your results with an diagnostic tool such as nRF Connect?

**Comment by Ganesh-210** [comment]
> > Thanks for the reply. I can get the name of paired Bluetooth devices.
> 
> What is your results with an diagnostic tool such as nRF Connect?

Check the attached image.

![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/155521009/2acf165d-6564-4d79-9d34-16c858f497da)

**Comment by axa88** [comment]
What I have been attempting to explain to you is that not all devices have a Name.
So to convince yourself that the devices that you claim to have a name, actually have a name, I suggest you download a tool like nRF Connect for your mobile device and compare those results with yours.

**Comment by Ganesh-210** [comment]
@axa88 Thanks ..it helped me a lot :D

**Comment by axa88** [comment]
> @axa88 Yeah I have downloaded the nRF Connect app and checked .My App results and nRF Connect app results are same.it helped me a lot :D

Great. Why not close the issue...

**Comment by Ganesh-210** [comment]
Done
