### ISSUE TITLE
WinUI UpdateRssi method shouldnt return true if the function isnt (currently) supported

### ISSUE THREAD

**Issue by axa88** [dotnet-bluetooth-le/dotnet-bluetooth-le#810]
It strikes me that until there is support on WinUI, this should return false 

```
 public override Task<bool> UpdateRssiAsync()
 {
     //No current method to update the Rssi of a device
     //In future implementations, maybe listen for device's advertisements

     Trace.Message("Request RSSI not supported in Windows");

     return Task.FromResult(true);
 }
```

**Comment by smsissuechecker** [comment]
Hi @axa88,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
> It strikes me that until there is support on WinUI, this should return false

Yes, I think you're right. It's easy to fix that. PR welcome ;)

**Comment by axa88** [comment]
> > It strikes me that until there is support on WinUI, this should return false
> 
> Yes, I think you're right. It's easy to fix that. PR welcome ;)

LoL. Alright... I'll see to finally making a fork and push this one out.

**Comment by axa88** [comment]
> > It strikes me that until there is support on WinUI, this should return false
> 
> Yes, I think you're right. It's easy to fix that. PR welcome ;)

Ive now tried to pull and build several times, I just cannot and dont have the time to figure out what is wrong with my environment.
Problems from missing versions of out of support frameworks (.netcore 5?) to other ambiguous errors i cant resolve...

@janusw 
Please feel free to make this change if possible
