### ISSUE TITLE
Documentation issue in README.md: "Allways" needs to be replaced with "Always"

### ISSUE THREAD

**Issue by abergquist** [dotnet-bluetooth-le/dotnet-bluetooth-le#813]
"Allways" needs to be replaced with "Always" at the start of the following sentence found in https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/master/README.md:

> Allways **use GetServiceAsync and GetCharacteristicAsync to get a valid instance.**

**Comment by smsissuechecker** [comment]
Hi @abergquist,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
Fixed with 450dbc5cf96c2b2101b55ecf7d57002e9bbcba5e 😄
