### ISSUE TITLE
`ScanFilterOptions` filter returned devices on WinUI

### ISSUE THREAD

**Issue by axa88** [dotnet-bluetooth-le/dotnet-bluetooth-le#814]
`ScanFilterOptions` do not appear to work on WinUI.

For example on Android I am able to set this filter to only return Samsung devices:
ScanFilterOptions = new() { ManufacturerDataFilters = [new(0x0075)] }

Or this filter to return only a specific Service UUID
`ScanFilterOptions = new() { ServiceUuids = [GetUuid(0xe000)] }`

Or this to filter on a device name
`ScanFilterOptions = new() { DeviceNames = ["motoAppAratus"] }`

This leaves applying a `DeviceFilter` instead which does work.

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Create a scan with any of the above filters

2. Observe it works with Android but not on WinUI

3.

## Expected behavior
`ScanFilterOptions` filter returned devices on WinUI

## Expected behavior
`ScanFilterOptions` do not filter returned devices on WinUI

### Crashlog

No crashes

## Configuration

**Version of the Plugin:**
v3.0.0

**Platform:** 
Not working .NET8 Win10.0.19041.0 
Working on .NET8 Android 12/13 target 34

**Device:** IBM X1 carbon 1, Samsung A11, Samsung A51

**Comment by smsissuechecker** [comment]
Hi @axa88,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
> `ScanFilterOptions` do not appear to work on WinUI.

Yes, as documented ...

https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/112a1eaf4bde674842626abdcd4247d583a0e221/Source/Plugin.BLE/Shared/ScanFilterOptions.cs#L72-L76


> For example on Android I am able to set this filter to only return Samsung devices: ScanFilterOptions = new() { ManufacturerDataFilters = [new(0x0075)] }

https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/112a1eaf4bde674842626abdcd4247d583a0e221/Source/Plugin.BLE/Shared/ScanFilterOptions.cs#L93-L96


> Or this filter to return only a specific Service UUID `ScanFilterOptions = new() { ServiceUuids = [GetUuid(0xe000)] }`

https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/112a1eaf4bde674842626abdcd4247d583a0e221/Source/Plugin.BLE/Shared/ScanFilterOptions.cs#L78-L81


> Or this to filter on a device name `ScanFilterOptions = new() { DeviceNames = ["motoAppAratus"] }`

https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/blob/112a1eaf4bde674842626abdcd4247d583a0e221/Source/Plugin.BLE/Shared/ScanFilterOptions.cs#L98-L101


Reminder: The only difference between a bug and a feature is documentation. So what you're reporting here is actually a feature 😜

(Sure, would be good to implement these scan filtering options on Windows as well. I don't know if the Windows BLE APIs allow that. Pointers welcome ...)
