### ISSUE TITLE
WinUI AdvertisementRecords missing advertised device records

### ISSUE THREAD

**Issue by axa88** [dotnet-bluetooth-le/dotnet-bluetooth-le#815]
It appears to me there is an issue with collection of `IDevice.AdvertisementRecords` while scanning on `WinUI`.

I have found when a device advertises, `WinUI` the `AdvertisementRecords` will tend to intermittently lose/be overwritten by other `AdvertisementRecords` upon each subsequent `Adapter.DeviceAdvertised` events received.  And rarely if ever do all advertised data appear in the `AdvertisementRecords` at the same time.

Im unsure if this is a OS/hardware limitation but here are my observations.

Here is my esp32 device advertising 4 separate `AdvertisementRecord`s
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/13371986/5ab7cbd7-bcc4-4067-a476-660eb0b6ac36)

And Here is my MAUI app running on `Android` will list all 4 devices as they are found in `IDevice.AdvertisementRecords` upon `Adapter.DeviceDiscovered` event, as well as every subsequent `Adapter.DeviceAdvertised` event raised.

![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/13371986/6c715cc1-bef4-4efb-9fd2-2dbb65b249f1)

While the same application running on `WinUI` will only list part of the advertised Records upon `Adapter.DeviceDiscovered` and each subsequent `Adapter.DeviceAdvertised` event raised.  Or may have a record missing completely. 
Here, the 4 Records were consistently split into 2 different distributions, 3 records, and 1 record:

![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/13371986/daded88a-c348-44e2-8b49-4c2dedd63642)

I couldn't observe any pattern to the inconsistency, any event might return either the 1 record or 3 records.

Note the advertisement pack over 31 bytes; could this be getting broken up by the underlying BLE stack causing inconsistency on the different platforms?
So I wonder if this issue relates to #814 where Ive found `ScanFilterOptions` to also not work on `WinUI`

## Expected behavior
`IDevice.AdvertisementRecords` should consistently list all records provided by a device after initial `Adapter.DeviceDiscovered` and each subsequent `Adapter.DeviceAdvertised` event raised.

## Actual behavior
`IDevice.AdvertisementRecords` somewhat randomly list a partial distribution of all available records, seemingly changing upon `Adapter.DeviceDiscovered` and each subsequent `Adapter.DeviceAdvertised` event raised.

### Crashlog

No crashes

## Configuration

**Version of the Plugin:**
v3.0.0

**Platform:** 
Not working .NET8 Win10.0.19041.0 
Working on .NET8 Android 12/13 target 34

**Device:** IBM X1 carbon 1, Samsung A11, Samsung A51

**Comment by smsissuechecker** [comment]
Hi @axa88,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by axa88** [comment]
@janusw 

Ill dig out the firmware and change the Advertising PDU payload to 31 bits or less and see what changes.
As far as what i know for sure, the BLE peripheral that is advertising,  ESP32 (ESP32-D0WD-V3 (revision 3)) => BLE 4..2 => so it doesn't support extended Advertising.  Just as reported on my A51 Android ble 4.2 device, but that platform does collect all in `AdvertisementRecords`

My windows device Windows X1 carbon gen 6 => BLE 4.1 fwiw, so its at least a windows issue in this case.

The work around is to collect all the records starting with the initial device on and `DeviceDiscovered` and add to it with each `DeviceAdvertised` event

This seems to work well but dont know if that's an appropriate thing to do overall if not positive of the underlying issue.

**Comment by axa88** [comment]
@janusw 

> If extended advertising is supported at some Windows API level, this method needs to be properly implemented on Windows.

What about [System.DeviceInterface.Bluetooth.ProductVersion](https://learn.microsoft.com/en-us/windows/win32/properties/props-system-deviceinterface-bluetooth-productversion)  Then testing for version >= 5 ? 

I guess there might be more to it than just testing the version, otherwise Android and iOS might just return the version and not have a dedicated calls for extended advertising support

**Comment by axa88** [comment]
Sure enough shortening the advertisement to non extended limitations this packet fragmentation no longer seem to manifest on windows.

Ive no real idea how a device that doesn't support extended advertisements, ESP32 BLE 4.2, manages to send _all_ of data over spec limit of 31 byte payload, but it seems Android gathers the data correctly while windows doesn't.

**Comment by janusw** [comment]
> > If extended advertising is supported at some Windows API level, this method needs to be properly implemented on Windows.
> 
> What about [System.DeviceInterface.Bluetooth.ProductVersion](https://learn.microsoft.com/en-us/windows/win32/properties/props-system-deviceinterface-bluetooth-productversion) Then testing for version >= 5 ?
> 
> I guess there might be more to it than just testing the version.

Right. Testing the supported BLE version is not enough here. An adapter might only support specifc features of BLE 5, but not all of them.

The necessary API endpoint for checking support for extended advertising on Windows seems to be this one:

https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothadapter.isextendedadvertisingsupported

**Comment by axa88** [comment]
Closing this. It seems that it may be inherent to Windows that Discovered devices are returned to the API quickly and may not contain all associated Advertisement data.  There seems to be a delay or at least the option to delay (using the MATCH_MODE parameter) before most if not all associated advertisements had been received. 

If i a similar option on Windows is found it might be revisited.
