### ISSUE TITLE
GetCharacteristicAsync returning null for iOS, not Android. Characteristic missing from iOS only

### ISSUE THREAD

**Issue by nathenxbrewer** [dotnet-bluetooth-le/dotnet-bluetooth-le#816]
I am developing an app that utilizes BLE. I have a characteristic with UUID da6d0fee that resides in the da6d0fe1 service. When I 
call service.GetCharacteristicAsync, it is returning null. This is not happening on all of our products so I'm not sure what is going on here. The characteristic is present in nrfConnect.

![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/43285863/2cb781f1-5a1f-4004-b28e-4f7f94552941)

nrfConnect for iOS shows it's missing as well
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/43285863/346f2741-b4a4-46dc-a8f9-4c3752b4bfa6)

Plugin.BLE reports 7 characteristics in this service, and the 7th ends at da6d0fed. 
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/43285863/5e472a25-01bf-475d-b8fd-11f954b29745)

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
3.1.0-beta.2

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
iOS 17.3.1

**Device:** e.g. HTC Sensation /i Phone 7 ...
iPhone 15 Pro Max

**Comment by smsissuechecker** [comment]
Hi @nathenxbrewer,

I'm the friendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by axa88** [comment]
> The characteristic is present in nrfConnect.

> nrfConnect for iOS shows it's missing as well

This is confusing.  Are you trying to say the characteristic is present in nRF on (an)other platform(s), but not iOS?

interesting. though nRF is the gold standard, if its also missing the characteristic, i wouldn't at all expect its an issue of this library.

**Comment by nathenxbrewer** [comment]
I ended up rebooting the phone a few times and it came back. Must have been the OS caching the values. I had just finished a Firmware update on the device and that characteristic was not present in earlier firmware versions.
