### ISSUE TITLE
Enable/disable Bluetooth on Android

### ISSUE THREAD

**Issue by janusw** [dotnet-bluetooth-le/dotnet-bluetooth-le#821]
This is a follow-up to PR #784, which introduced a method `IBluetoothLE.TrySetStateAsync` for enabling or disabling the Bluetooth radio (and only implemented it on Windows for the start).

It seems that this should also be possible on Android, via the method mentioned here:
https://stackoverflow.com/questions/76858093/how-to-activate-deactivate-bluetooth-in-net-maui

Would be great to have this implemented. 😃

**Comment by smsissuechecker** [comment]
Hi @janusw,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
@axa88 Would you like to look into this? Otherwise I might take a stab ...

**Comment by axa88** [comment]
> @axa88 Would you like to look into this? Otherwise I might take a stab ...

It's certainly on my radar.

**Comment by midoragh** [comment]
JFI: I implemented this on App level because starting with Android 13 (API 33) you you are no longer allowed to call the method to enable/disable BLE (var setStateOnOff = bleCurrent.GetType().GetMethod("SetStateOnOff");).
Instead you have to call something like
StartActivityForResult(intentBtEnabled, REQUEST_ENABLE_BT);
in an Activity. This call will popup a request to the user if he likes to switch on BLE.

**Comment by janusw** [comment]
> JFI: I implemented this on App level because starting with Android 13 (API 33) you you are no longer allowed to call the method to enable/disable BLE (var setStateOnOff = bleCurrent.GetType().GetMethod("SetStateOnOff");).

Yes, the enable/disable methods of the BluetoothAdapter are deprecated in API 33:

https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable()

> Instead you have to call something like StartActivityForResult(intentBtEnabled, REQUEST_ENABLE_BT); in an Activity. This call will popup a request to the user if he likes to switch on BLE.

I assume you mean `BluetoothAdapter.ACTION_REQUEST_ENABLE`, which was suggested in the Stackoverflow thread mentioned above.

https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#ACTION_REQUEST_ENABLE

**Comment by axa88** [comment]
> @axa88 Would you like to look into this? Otherwise I might take a stab ...

@janusw I'm jammed with work for the foreseeable future and not up to speed on the workings of this library.  Please feel free to implement at your convenience. 

And while at it perhaps confirm the `IBluetooth` `State` properties and event on `WinUI`.  I'm pretty confident there is issue

**Comment by janusw** [comment]
> @janusw I'm jammed with work for the foreseeable future and not up to speed on the workings of this library. Please feel free to implement at your convenience.

Ok, thanks for letting me know. I have just opened PR #823 for it (and would be grateful for some testing and feedback) ....

**Comment by janusw** [comment]
Fixed via #823.
