### ISSUE TITLE
Can't detect device

### ISSUE THREAD

**Issue by vfiksdal** [dotnet-bluetooth-le/dotnet-bluetooth-le#830]
Hi, and thanks for a very nice library :-)

I'm trying to use the BLE.Client.MAUI example to detect a custom hardware with a fairly standard BLE compliant chipset. I'm pretty sure the scanner itself works as intended, because it's picking up my headset, tv etc. Unfortunately it fails to detect the intended hardware. Said hardware is detected by Windows itself, a legacy UWP app, as well as a couple of third party BT scanners I downloaded (With bluetooth address 00:13:43:BE:43:CB), but not by the MAUI app.

This problem would be difficult to reproduce as it relies on custom hardware, but maybe you would be able to give me some pointers as to how I could address the problem? I've tried changing the ScanMode and ScanMatchMode parameters, but I don't really see any other alternatives.

**Comment by smsissuechecker** [comment]
Hi @vfiksdal,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
Two questions:
* Could you try `BLE.Client.MAUI` on a different operating system, in order to check if you see the device there? Android might be the easiest, but iOS and MacOS are also supported (if you have access to an Apple device).
* How does the device advertise itself? What kind of data does the advertisement include?

**Comment by vfiksdal** [comment]
Hi, and thanks for a swift reply to a rather unreasonable report :-)

Good idea, I'll try to get the project and/or your sample project loaded onto my tablet over the weekend. It's a couple of years old though, so it may have some hoops of it own to overcome.

As for the advertisement I don't really know much about it, maybe you can recommend a third party app which provides more in-depth details? I just randomly downloaded Medeival Bluetooth Network Scanner (Which in retrospect doesn't sound too promising)  and it provided the following data:
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/51258725/862da8c7-5157-4f8e-b1cd-f0a0e9691fa2)
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/51258725/8a6ecacf-a6a7-48c2-8e00-d1bd8ff0ba2d)

Thanks again, and I'll get back to you ASAP on how it works on Android.

**Comment by janusw** [comment]
> As for the advertisement I don't really know much about it, maybe you can recommend a third party app which provides more in-depth details?

nRF Connect is a pretty good tool. I mostly used it on Android, but it seems there is also a Desktop variant that runs on Windows:

https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-desktop

> I just randomly downloaded Medeival Bluetooth Network Scanner (Which in retrospect doesn't sound too promising) and it provided the following data: 

It seems this doesn't show any details on the actual advertisement data. nRF Connect will be able to reveal that.

**Comment by vfiksdal** [comment]
Unfortunately, I can't get this tool to scan in Windows. Might be because I have several systems running a newer version of JLink.

It did work in Android though, and interestingly it doesn't detect the device either. Android itself do find the device though, so the radio itself is not the problem.

Can this be some kind of compliance issue? The datasheet for the chipset says it's 4.2 compliant. That's kind of old now?

**Comment by janusw** [comment]
> It did work in Android though, and interestingly it doesn't detect the device either. Android itself do find the device though, so the radio itself is not the problem.

Just to clarify what you are talking about: Did you try nRF Connect or BLE.Client.Maui on Android? If the Android OS sees the device, then both of these tools should in theory see it as well (unless it's a Bluetooth Classic device, which does not support BLE) ...

**Comment by vfiksdal** [comment]
It's nRF Connect that failed to detect it. I'll need to set permissions etc to get my own project running on android, and haven't gotten around to it yet.

The chipset supports both LE and Classic, and the firmware does specify that it uses LE, but it may be using Classic due to a bug. Do you know a simple way to identify this?

Thanks a lot for your help again.

**Comment by vfiksdal** [comment]
Looking at the firmware source, it seems like it is indeed BLE. All of these are enabled:

 * Bit 0 - Enable / Disable LE Secure connection.
 * Bit 1 - Enable / Disable LL Connection parameter request.
 * Bit 2 - Enable / Disable LL ping procedure (Supported only in TC35680/81).
 * Bit 3 - Enable / Disable Support for 2M PHY (Supported only in TC35680/81).
 * Bit 4 - Enable / Disable Support for LE Coded PHY (Supported only in TC35680/81).
 * Bit 5 - Enable / Disable Support for LE Extended Advertising (Supported only in TC35680/81).
 * Bit 6 - Enable / Disable Support for LE Data length change event (Supported only in TC35680/81).

I assume "secure connection" means encrypted, but this should not apply to the discovery?

**Comment by axa88** [comment]
> It's nRF Connect that failed to detect it.

fwiw, nRf on android is the gold standard imho.
If your devices isnt detectable with that, it either doesn't want to be found or more likely something about the device is incompatible

**Comment by vfiksdal** [comment]
Apparantly outside the scope of the library. Thank you for your input on the issue.
