### ISSUE TITLE
Cannot use the package with Avalonia Cross Platform Project

### ISSUE THREAD

**Issue by UrSok** [dotnet-bluetooth-le/dotnet-bluetooth-le#833]
## Steps to reproduce

1. Create a cross platform avalonia project.
2. Run it.

## Expected behavior
The projects runs.

## Actual behavior
An exception is thrown.
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/5286851/cce57560-0418-4917-860e-512b1c11c2de)

### Crashlog

System.NotImplementedException
  HResult=0x80004001
  Message=This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  Source=Plugin.BLE
  StackTrace:
   at Plugin.BLE.CrossBluetoothLE.get_Current()
   at Smart.Galaxy.Star.App.ViewModels.MainViewModel..ctor() in Y:\repos\Smart.Galaxy.Star.App\Smart.Galaxy.Star.App\ViewModels\MainViewModel.cs:line 16
   at Smart.Galaxy.Star.App.App.OnFrameworkInitializationCompleted() in Y:\repos\Smart.Galaxy.Star.App\Smart.Galaxy.Star.App\App.axaml.cs:line 21
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Smart.Galaxy.Star.App.Desktop.Program.Main(String[] args) in Y:\repos\Smart.Galaxy.Star.App\Smart.Galaxy.Star.App.Desktop\Program.cs:line 15

## Configuration

**Version of the Plugin:** 3.1.0-beta.3

**Platform:** Windows 11 22635.3420

**Comment by axa88** [comment]
there's support for Avalonia ?

**Comment by janusw** [comment]
Hm, I'm not very familiar with Avalonia. I guess the most important question is: Which .NET target framework are you using? And maybe: Which Avalonia version?

**Comment by UrSok** [comment]
I'm using the latest stable version(11.0.10) of Avalonia.
I created the solution using their [extension](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaVS).

All the created projects use .NET 8 as their target:
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/5286851/3d50d09d-1487-48e0-a1cb-38e9f732696a)

**Comment by janusw** [comment]
> I'm using the latest stable version(11.0.10) of Avalonia. I created the solution using their [extension](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaVS).
> 
> All the created projects use .NET 8 as their target:

Thanks for the info. I created a solution from the Avalonia template myself by now (on MacOS using VSCode with the "Avalonia for VSCode" extension).

I assume the .Android and .iOS projects should work well with Plugin.BLE, since they target `net8.0-android` and `net8.0-ios`, respectively. I haven't actually tried it, though.

The .Desktop project, however, which you apparently tried to run on Windows, is probably not working because it uses

```
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
```

The .Desktop project template also includes this comment:

```
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
```

If you follow this advice and use a project with target framework `net8.0-windows`, I assume that this should work with Plugin.BLE on Windows. (Same for MacOS. Linux is currently not supported by Plugin.BLE.)

Could you try that and let us know whether you got it to work?

**Comment by UrSok** [comment]
Yes, it does work, I had to also select the Target OS version for it to work.

Thank you for your help!

**Comment by janusw** [comment]
> Yes, it does work

Awesome, thanks for the feedback. I guess we can close this issue then.

> Thank you for your help!

You're welcome :)
