### ISSUE TITLE
Regarding Plugin.BLE Connection Event

### ISSUE THREAD

**Issue by DhairyaOza005** [dotnet-bluetooth-le/dotnet-bluetooth-le#835]
So i have included Plugin.BLE as Nuget package for BLE Connection and retrieving data from a device from it. Device has wait , enabled , disabled mode and BLE can be connected when enabled mode is on

Now what is happening is the particular device even when its on Wait Mode ( Its configuration of turning ble things on ) Plugin.ble can connect with it and Device_connected event is raised and but as we know the device is not connected so connetion_lost event is raised after like 5-6 seconds which is fair but how come device is connecting first .....it should give connection_error event raised.

public async Task<bool> ConnectBleDevice(ScannedDeviceInfo selectedDevice)
        {
            
                try
                {
                    TimeSpan timeout = TimeSpan.FromSeconds(10);

                    await _bleAdapter.StopScanningForDevicesAsync();

                    // Create a CancellationTokenSource with the specified timeout
                    using (var cancellationTokenSource = new CancellationTokenSource(timeout))
                    {
                        await _bleAdapter.ConnectToDeviceAsync(selectedDevice.BleDevice, new ConnectParameters(false, false), cancellationTokenSource.Token);
                    }

                    _bleDevice = selectedDevice.BleDevice;
                    
                return true;
                }
                catch (TaskCanceledException)
                {
                    await DisconnectDevice();
                    await Shell.Current.DisplayAlert("Alert", "Device Communication error", "OK");
                    await Shell.Current.GoToAsync("../..");
                }
                catch (DeviceConnectionException ex)
                {
                    await DisconnectDevice();
                    await Shell.Current.DisplayAlert("Alert", "Device Communication error", "OK");
                    await Shell.Current.GoToAsync("../..");
                } 
            return false;
        }
        
Now what should i add here to make sure that device is connected when its in only enabled mode and not in wait mode.
Thanks for help

**Comment by smsissuechecker** [comment]
Hi @DhairyaOza005,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
