### ISSUE TITLE
[WinUI] Adapter.DeviceConnected event is triggered n+1 times upon each subsequent Device Disconnect/Connect cycle

### ISSUE THREAD

**Issue by axa88** [dotnet-bluetooth-le/dotnet-bluetooth-le#841]
Ive come to realize on `WinUI`, with each subsequent connection and disconnection to a single `Device`, an additional trigger of the `Adapter.DeviceConnected` `event` will occur.

Meaning on the first connection, the event is triggered as expected.
`Disconnect` and `Connect` again, upon connection the `event` will trigger twice...
`Disconnect` and `Connect` again, upon connection the `event` will trigger three times....
So on and so fourth

Tested on Android this doesn't occur.

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

Any programming should replicate this on `WinUI`

## Steps to reproduce

1. Set breakpoint on Adapter.DeviceConnected event

2. Connect, Disconnect, Connect again

3. Observe multiple events triggered.
Repeat as many times as you would like

## Expected behavior
On each subsequent Connection, an additional trigger of the event occurs

## Actual behavior
On each subsequent Connection, a one one trigger of the event should occur

### Crashlog

no crash

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
3.0.0

**Platform:**
Windows 10.0.19041

**Device:** 
Device name	Portable
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.86 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by smsissuechecker** [comment]
Hi @axa88,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by axa88** [comment]
Attempted to mitigate this issue by unsubscribing to the `Adapter.DeviceConnected` `event` within the event handler, and then resubscribing during the `Adapter.DeviceDisconnected` event handler.

But it seems not possible to resubscribe to the event a second time... or at least cannot do it during the `DeviceDisconnected` `event`.

Not sure where to go with this

**Comment by janusw** [comment]
So you are seeing this with version 3.0.0? Does 3.1.0-rc.1 behave the same way?

**Comment by janusw** [comment]
It sounds like the event is not properly unsubscribed when disconnecting.

**Comment by axa88** [comment]
> So you are seeing this with version 3.0.0? Does 3.1.0-rc.1 behave the same way?

figured it would be asked... ill have to try asap

**Comment by axa88** [comment]
> It sounds like the event is not properly unsubscribed when disconnecting.

Ya this issue seems to be multifaceted...
The n+1 as well as the failure to unsub.
