### ISSUE TITLE
Windows: Check OS version runtime

### ISSUE THREAD

**Issue by AskBojesen** [dotnet-bluetooth-le/dotnet-bluetooth-le#852]
Windows: Check OS version number.

BLE version = 3.1.0-rc1

Currently a runtime on the Windows client needs > 22000
Eg. to call this: https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothlepreferredconnectionparameters
Unfortunately Windows allow executing code linked to > 22000 - only at runtime calling new functionality causes error.

1. Run on a Windows 10
2. Connect to an instrument

# Expected behavior
Connected without errors

# Actual behavior
Cannot connect

**Comment by smsissuechecker** [comment]
Hi @AskBojesen,

I'm the friendly issue checker.
It seems like (75.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
I think this is a regression, which has been introduced in 3.1.0-beta.2 via #801. It should be fixed before we release the final version 3.1.0.

**Comment by janusw** [comment]
See also the discussion in #849 ...

**Comment by AskBojesen** [comment]
Ok, I will make a draft PR today to fix this

**Comment by AskBojesen** [comment]
PR: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/pull/853
