### ISSUE TITLE
Bluetooth stack breaks when trying connect on phone boot

### ISSUE THREAD

**Issue by alex3696** [dotnet-bluetooth-le/dotnet-bluetooth-le#854]
Some devices load cache of previously connected devices **slowly**.
When you try to ConnectToDeviceAsync while loading the cache, the bluetooth stack of the device completely breaks.
Before connecting, you should check the device type to avoid this break. Check Source/Plugin.BLE/Android/Adapter.cs ConnectToKnownDeviceNativeAsync . BluetoothDeviceType must be Le or Dual not Unknown!

```
public override async Task<IDevice> ConnectToKnownDeviceNativeAsync(Guid deviceGuid, ConnectParameters connectParameters = default(ConnectParameters), CancellationToken cancellationToken = default(CancellationToken))
{
    var macBytes = deviceGuid.ToByteArray().Skip(10).Take(6).ToArray();
    var nativeDevice = _bluetoothAdapter.GetRemoteDevice(macBytes);
    if (nativeDevice == null
      || !(BluetoothDeviceType.Le == nativeDevice.Type || BluetoothDeviceType.Dual == nativeDevice.Type) /* Check the device type */ )
        throw new Abstractions.Exceptions.DeviceConnectionException(deviceGuid, "", $"[Adapter] Device {deviceGuid} not found.");
    var device = new Device(this, nativeDevice, null);

    await ConnectToDeviceAsync(device, connectParameters, cancellationToken);
    return device;
}
```

## Steps to reproduce

1. Reboot device
2. wait 2 or 3 minutes
3. Start any your app and connect to any BLE device (exsamle Source/BLE.Client : DeviceListPage.xaml button "Connect to previous" calls Adapter.ConnectToKnownDeviceAsync -> ConnectToKnownDeviceNativeAsync) - it is OK
4. Reboot device
5. do not wait, Start any your app and start connection to BLE device. 

## Actual behavior
Phone Bluetooth stack breaks and does not work at all until the next reboot - unable to connect any BLE devices.

## Expected behavior
Bluetooth devices connect and function normally

## Configuration
**Version of the Plugin:** all: 2 and 3
**Platform:** Android 9+
**Device:** china phones: IIIF150 https://www.iiif150.com/

**Comment by smsissuechecker** [comment]
Hi @alex3696,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
> Some devices load cache of previously connected devices **slowly**. When you try to ConnectToDeviceAsync while loading the cache, the bluetooth stack of the device completely breaks. Before connecting, you should check the device type to avoid this break. Check Source/Plugin.BLE/Android/Adapter.cs ConnectToKnownDeviceNativeAsync . BluetoothDeviceType must be Le or Dual not Unknown!
> 
> ```
> public override async Task<IDevice> ConnectToKnownDeviceNativeAsync(Guid deviceGuid, ConnectParameters connectParameters = default(ConnectParameters), CancellationToken cancellationToken = default(CancellationToken))
> {
>     var macBytes = deviceGuid.ToByteArray().Skip(10).Take(6).ToArray();
>     var nativeDevice = _bluetoothAdapter.GetRemoteDevice(macBytes);
>     if (nativeDevice == null
>       || !(BluetoothDeviceType.Le == nativeDevice.Type || BluetoothDeviceType.Dual == nativeDevice.Type) /* Check the device type */ )
>         throw new Abstractions.Exceptions.DeviceConnectionException(deviceGuid, "", $"[Adapter] Device {deviceGuid} not found.");
>     var device = new Device(this, nativeDevice, null);
> 
>     await ConnectToDeviceAsync(device, connectParameters, cancellationToken);
>     return device;
> }
> ```

Great that you not only observed the problem, but already drafted a fix. 👍 
Do you feel confident enough to open a pull request with this change?
