### ISSUE TITLE
It doesn't work with android 14

### ISSUE THREAD

**Issue by yj320696** [dotnet-bluetooth-le/dotnet-bluetooth-le#860]
It works in old android version. 
When I tested it on android 14, after scanning, nothing was found.

**Comment by smsissuechecker** [comment]
Hi @yj320696,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
