### ISSUE TITLE
Feature Request: Bonding/Pairing on ios and Android

### ISSUE THREAD

**Issue by electro-logic** [dotnet-bluetooth-le/dotnet-bluetooth-le#867]
Would be great to have a way to pair a device from the code without manually doing it from the system settings page.

**Comment by smsissuechecker** [comment]
Hi @electro-logic,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by axa88** [comment]
public abstract Task BondAsync(IDevice device);

**Comment by electro-logic** [comment]
Hello, BondAsync is not working on Android

**Comment by axa88** [comment]
> Would be great to have a way to pair a device from the code without manually doing it from the system settings page.

are you using the latest version?

**Comment by janusw** [comment]
> Hello, BondAsync is not working on Android

It should. What are you trying to do? And what happens when you do it? Do you get any error messages or exceptions?

**Comment by electro-logic** [comment]
I tried again today

```
await Permissions.RequestAsync<Permissions.Bluetooth>();
var adapter = CrossBluetoothLE.Current.Adapter;
adapter.DeviceDiscovered += Adapter_DeviceDiscovered;
await adapter.StartScanningForDevicesAsync();
// ...
await adapter.BondAsync(e.Device);
await adapter.ConnectToDeviceAsync(e.Device);
```

and seems working fine. Thank you anyway.
