### ISSUE TITLE
Is Plugin.BLE only scan LE device,not suit Classic Blue Device?

### ISSUE THREAD

**Issue by deyangwangyu** [dotnet-bluetooth-le/dotnet-bluetooth-le#874]
target: android 12.0 API31
I follow the guide make a test project. The scan result only contain smart ring,not contain my phone and bluetooth module(HC-06)

BTW, I didn't put
'uses-feature android:name="android.hardware.bluetooth_le" android:required="true" ' into AndroidManifest.xml

**Comment by smsissuechecker** [comment]
Hi @deyangwangyu,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by deyangwangyu** [comment]
邮件已收到，谢谢！

**Comment by axa88** [comment]
> target: android 12.0 API31 I follow the guide make a test project. The scan result only contain smart ring,not contain my phone and bluetooth module(HC-06)
> 
> BTW, I didn't put 'uses-feature android:name="android.hardware.bluetooth_le" android:required="true" ' into AndroidManifest.xml

Well, that is what the "le" in dotnet-bluetooth-**_le_** means....

**Comment by janusw** [comment]
Yes, BLE only, no classic Bluetooth ...

**Comment by deyangwangyu** [comment]
邮件已收到，谢谢！
