### ISSUE TITLE
Access to TPermission

### ISSUE THREAD

**Issue by jbeen25** [dotnet-bluetooth-le/dotnet-bluetooth-le#878]
Straightforward request, can we get TPermission to be publically accessible?

All I want to do is run the following code:

```csharp
public async Task<bool> RequestPermissions<T>() where T : TPermission
{
	PermissionStatus status = await Permissions.CheckStatusAsync<T>();

	if (status != PermissionStatus.Granted)
	{
		status = await Permissions.RequestAsync<T>();

		if (status != PermissionStatus.Granted)
			return false;
	}

	return true;
}
```

**Comment by smsissuechecker** [comment]
Hi @jbeen25,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by jbeen25** [comment]
Never mind. I am now realized needed to use `BasePermissions, new()`.
