### ISSUE TITLE
iOS 18.0 still displays [?] in many scripts

### ISSUE THREAD

**Issue by Ashtontameirao** [dotnet-bluetooth-le/dotnet-bluetooth-le#885]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## New Noto Fonts for iOS 18 (New System Fonts apple adds to display on every supported iOS 18 device)
- Noto Sans Vithkuqi
- Noto Sans Old Sogdian
- Noto Sans Sogdian
- Noto Serif Old Uyghur
- Noto Sans Chorasmian
- Noto Sans Elymaic
- Noto Serif Dogra
- Noto Serif Dives Akuru
- Noto Sans Nandinagari
- Noto Sans Zanabazar Square
- Noto Sans Soyombo
- Noto Serif Makasar
- Noto Sans Kawi
- Noto Sans Cypro Minoan
- Noto Sans Anatolian Hieroglyphs
- Noto Sans Tangsa
- Noto Sans Medefaidrin
- Noto Serif Tangut
- Noto Serif Khitan Small
- Noto Sans Nushu
- Noto Znamenny Notation
- Noto Music
- Noto Sans Mayan Numerals
- Noto Sans SignWriting
- Noto Serif Toto
- Noto Sans Nag Mundari
- Noto Sans Indic Siyaq Numbers
- Noto Serif Ottoman Siyaq

## Steps to reproduce

1.

2.

3.

## Expected behavior
Apple needs to add new noto fonts to iOS 18 so it can display on every iOS 18 device.

## Actual behavior
No new unicode characters and scripts get added to display on websites and apps.

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
iOS 18.0

**Device:** e.g. HTC Sensation /i Phone 7 ...
iPhone 13 Pro
![WIN_20240808_12_20_08_Pro](https://github.com/user-attachments/assets/13ca07a5-410b-4b88-9d44-e67f546a37ca)

**Comment by smsissuechecker** [comment]
Hi @Ashtontameirao,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by axa88** [comment]
what?

**Comment by janusw** [comment]
Obviously not related to dotnet-bluetooth-le (or to BLE in general). Seems like you somehow picked the wrong project to open this issue ...
