### ISSUE TITLE
Unable to retrieve characteristic data from slave sensor

### ISSUE THREAD

**Issue by scyfla1** [dotnet-bluetooth-le/dotnet-bluetooth-le#895]
I'm happy to attach more code but first hoping someone familiar with this scenario may be able to point me to documentation or an obvious thing I'm missing. 

I have a ble device that has several sensors plugged into it. This device acts as the master and the sensors the slaves. 

Using Maui with Plugi.BLE I'm able to connect to the device, identify each of the sensors and subscribe to them. I've added a value updated method but this is never called. If I try to extract any data from the characteristic I get nothing. 

Has anyone had experience utilizing Plugin.BLE in this manner? If so how were you able to extract data? All the code thus far is working without error. 

The code below is located in a separate class so the portion that's connecting to the device in in the main page.

I appreciate any insight and apologize this is a bit fragmented. Just scratching my head at how to pull it together. 

`var characteristic = await service.GetCharacteristicAsync(characteristicUuid);
if (characteristic == null)
{
    Console.WriteLine($"Characteristic {characteristicUuid} not found.");
    return;
}

if (!characteristic.CanUpdate)
{
    Console.WriteLine($"Characteristic {characteristicUuid} does not support notifications.");
    return;
}

characteristic.ValueUpdated += (s, e) =>
{
    var sensorData = e.Characteristic.Value;
    if (sensorData != null && sensorData.Length > 0)
    {
        Console.WriteLine($"Received data from {characteristicUuid}: {BitConverter.ToString(sensorData)}");
    }
    else
    {
        Console.WriteLine($"No data received from {characteristicUuid}");
    }
};

await characteristic.StartUpdatesAsync();
Console.WriteLine($"Started updates for characteristic {characteristicUuid}");

var descriptor = await characteristic.GetDescriptorAsync(ClientCharacteristicConfigUuid);
if (descriptor != null)
{
    await descriptor.WriteAsync(new byte[] { 0x01, 0x00 });
    Console.WriteLine($"Enabled notifications for characteristic {characteristicUuid}");
}`

**Comment by smsissuechecker** [comment]
Hi @scyfla1,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
